### ISSUE TITLE
Indicate values that aren't doing anything by making the bars gray?

### ISSUE THREAD

**Issue by clydeshaffer** [nickgirardo/gt-sound-sculptor#6]
If an operator's AMP is zero then it's PITCH isn't doing anything, but I also realized that if an operator's AMP is zero then all of the operators preceding it aren't doing anything even if their AMP is nonzero.

So maybe it could be useful to change the color of their bar to gray whenever the value wouldn't actually be contributing to the outgoing sound

**Comment by nickgirardo** [comment]
This is a pretty good idea!  I'll try to get this implemented tomorrow

**Comment by nickgirardo** [comment]
Implemented by pr #11 !!
